// packages/shared-library/src/components/Button.tsx
import React from 'react';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  loading?: boolean;
  children: React.ReactNode;
}

const variantStyles: Record<string, React.CSSProperties> = {
  primary: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    border: 'none',
  },
  secondary: {
    background: '#f7fafc',
    color: '#2d3748',
    border: '1px solid #e2e8f0',
  },
  danger: {
    background: '#e53e3e',
    color: 'white',
    border: 'none',
  },
  ghost: {
    background: 'transparent',
    color: '#667eea',
    border: 'none',
  },
};

const sizeStyles: Record<string, React.CSSProperties> = {
  sm: { padding: '6px 12px', fontSize: '0.875rem' },
  md: { padding: '10px 20px', fontSize: '1rem' },
  lg: { padding: '14px 28px', fontSize: '1.125rem' },
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  disabled,
  children,
  style,
  ...props
}) => {
  const baseStyle: React.CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    borderRadius: '8px',
    fontWeight: 500,
    cursor: disabled || loading ? 'not-allowed' : 'pointer',
    opacity: disabled || loading ? 0.6 : 1,
    transition: 'all 0.2s ease',
    ...variantStyles[variant],
    ...sizeStyles[size],
    ...style,
  };

  return (
    <button style={baseStyle} disabled={disabled || loading} {...props}>
      {loading && <Spinner size="sm" />}
      {children}
    </button>
  );
};

const Spinner: React.FC<{ size?: 'sm' | 'md' }> = ({ size = 'sm' }) => {
  const dimension = size === 'sm' ? 14 : 20;
  return (
    <svg
      width={dimension}
      height={dimension}
      viewBox="0 0 24 24"
      fill="none"
      style={{ animation: 'spin 1s linear infinite' }}
    >
      <circle
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
        strokeDasharray="32"
        strokeDashoffset="12"
      />
    </svg>
  );
};

// projects/shared-lib/src/lib/components/button/button.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ButtonVariant = 'primary' | 'secondary' | 'tertiary' | 'danger' | 'success';
export type ButtonSize = 'small' | 'medium' | 'large';

/**
 * Motif-styled Button Component
 * 
 * A reusable button component following Motif design patterns.
 * Supports multiple variants, sizes, and states.
 */
@Component({
  selector: 'lib-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      [type]="type"
      [class]="buttonClasses"
      [disabled]="disabled || loading"
      (click)="onClick.emit($event)"
      [attr.aria-label]="ariaLabel"
      [attr.aria-busy]="loading">
      @if (loading) {
        <span class="spinner"></span>
      }
      @if (icon && iconPosition === 'left') {
        <span class="icon">{{ icon }}</span>
      }
      <span class="label"><ng-content></ng-content></span>
      @if (icon && iconPosition === 'right') {
        <span class="icon">{{ icon }}</span>
      }
    </button>
  `,
  styles: [`
    button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      font-family: inherit;
      font-weight: 500;
      border: none;
      border-radius: 6px;
      cursor: pointer;
      transition: all 0.2s ease;
    }
    
    button:disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }
    
    /* Sizes */
    .size-small { padding: 6px 12px; font-size: 0.8rem; }
    .size-medium { padding: 10px 20px; font-size: 0.9rem; }
    .size-large { padding: 14px 28px; font-size: 1rem; }
    
    /* Variants */
    .variant-primary { background: var(--motif-primary, #1976d2); color: white; }
    .variant-primary:hover:not(:disabled) { background: var(--motif-primary-dark, #1565c0); }
    
    .variant-secondary { background: transparent; color: var(--motif-primary, #1976d2); border: 1px solid var(--motif-primary, #1976d2); }
    .variant-secondary:hover:not(:disabled) { background: rgba(25, 118, 210, 0.08); }
    
    .variant-tertiary { background: transparent; color: var(--motif-text-primary, #333); }
    .variant-tertiary:hover:not(:disabled) { background: rgba(0, 0, 0, 0.04); }
    
    .variant-danger { background: var(--motif-error, #f44336); color: white; }
    .variant-danger:hover:not(:disabled) { background: #d32f2f; }
    
    .variant-success { background: var(--motif-success, #4caf50); color: white; }
    .variant-success:hover:not(:disabled) { background: #388e3c; }
    
    .full-width { width: 100%; }
    
    .spinner {
      width: 16px;
      height: 16px;
      border: 2px solid rgba(255,255,255,0.3);
      border-top-color: white;
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
    }
    
    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'medium';
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() disabled = false;
  @Input() loading = false;
  @Input() fullWidth = false;
  @Input() icon?: string;
  @Input() iconPosition: 'left' | 'right' = 'left';
  @Input() ariaLabel?: string;
  
  @Output() onClick = new EventEmitter<MouseEvent>();
  
  get buttonClasses(): string {
    return [
      `variant-${this.variant}`,
      `size-${this.size}`,
      this.fullWidth ? 'full-width' : ''
    ].filter(Boolean).join(' ');
  }
}
