// projects/reg-reporting/src/app/components/reg-reporting-grid/reg-reporting-grid.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AgGridModule } from 'ag-grid-angular';
import { ColDef, GridReadyEvent, GridApi } from 'ag-grid-community';

import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';

interface RegReport {
  id: string;
  reportName: string;
  regulator: string;
  jurisdiction: string;
  frequency: string;
  dueDate: string;
  status: string;
  submittedDate: string | null;
}

@Component({
  selector: 'app-reg-reporting-grid',
  standalone: true,
  imports: [CommonModule, AgGridModule],
  template: `
    <div class="grid-container">
      <div class="grid-toolbar">
        <div class="toolbar-left">
          <button class="toolbar-btn" (click)="onRefresh()">🔄 Refresh</button>
          <button class="toolbar-btn" (click)="onExport()">📥 Export</button>
        </div>
        <div class="toolbar-right">
          <span class="record-count">{{ rowData.length }} reports</span>
          <span class="version-info">AG Grid v31</span>
        </div>
      </div>
      <div class="ag-theme-alpine grid-wrapper">
        <ag-grid-angular style="width: 100%; height: 500px;" [rowData]="rowData" [columnDefs]="columnDefs" [defaultColDef]="defaultColDef" [animateRows]="true" [pagination]="true" [paginationPageSize]="10" (gridReady)="onGridReady($event)"></ag-grid-angular>
      </div>
    </div>
  `,
  styles: [`
    .grid-container { padding: 16px 24px 24px; }
    .grid-toolbar { display: flex; justify-content: space-between; margin-bottom: 16px; }
    .toolbar-left { display: flex; gap: 8px; }
    .toolbar-btn { padding: 8px 12px; background: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 6px; cursor: pointer; }
    .toolbar-right { display: flex; align-items: center; gap: 16px; }
    .record-count { color: #6b7280; font-size: 0.9rem; }
    .version-info { padding: 4px 8px; background: #dbeafe; color: #2563eb; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }
    .grid-wrapper { border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class RegReportingGridComponent implements OnInit {
  private gridApi!: GridApi;
  
  rowData: RegReport[] = [
    { id: 'REG-001', reportName: 'Basel III Capital', regulator: 'Federal Reserve', jurisdiction: 'US', frequency: 'Quarterly', dueDate: '2024-03-31', status: 'Submitted', submittedDate: '2024-03-28' },
    { id: 'REG-002', reportName: 'CCAR Stress Test', regulator: 'Federal Reserve', jurisdiction: 'US', frequency: 'Annual', dueDate: '2024-04-05', status: 'In Progress', submittedDate: null },
    { id: 'REG-003', reportName: 'MiFID II', regulator: 'ESMA', jurisdiction: 'EU', frequency: 'Daily', dueDate: '2024-03-15', status: 'Submitted', submittedDate: '2024-03-15' },
    { id: 'REG-004', reportName: 'Dodd-Frank', regulator: 'SEC', jurisdiction: 'US', frequency: 'Monthly', dueDate: '2024-03-31', status: 'Pending', submittedDate: null },
    { id: 'REG-005', reportName: 'GDPR Compliance', regulator: 'ICO', jurisdiction: 'UK', frequency: 'Annual', dueDate: '2024-05-25', status: 'Not Started', submittedDate: null }
  ];
  
  columnDefs: ColDef<RegReport>[] = [
    { field: 'id', headerName: 'Report ID', width: 100, pinned: 'left' },
    { field: 'reportName', headerName: 'Report Name', flex: 1, minWidth: 180 },
    { field: 'regulator', headerName: 'Regulator', width: 130 },
    { field: 'jurisdiction', headerName: 'Jurisdiction', width: 100 },
    { field: 'frequency', headerName: 'Frequency', width: 100 },
    { field: 'dueDate', headerName: 'Due Date', width: 120 },
    { field: 'status', headerName: 'Status', width: 120 },
    { field: 'submittedDate', headerName: 'Submitted', width: 120 }
  ];
  
  defaultColDef: ColDef = { sortable: true, resizable: true, filter: true };
  
  ngOnInit(): void { console.log('[RegReportingGrid] Initialized with AG Grid v31'); }
  onGridReady(params: GridReadyEvent): void { this.gridApi = params.api; }
  onRefresh(): void { this.gridApi?.refreshCells(); }
  onExport(): void { this.gridApi?.exportDataAsCsv({ fileName: `reg-reports-${new Date().toISOString().split('T')[0]}.csv` }); }
}

// apps/reg-reporting/src/components/RegReportingGrid.tsx
import React, { useState, useCallback, useMemo } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ColDef, GridReadyEvent, GridApi } from 'ag-grid-community';

// Import AG Grid styles
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';

interface RegReport {
  id: string;
  reportName: string;
  reportType: string;
  status: 'Draft' | 'Submitted' | 'Approved' | 'Rejected';
  submissionDate: string;
  regulator: string;
  jurisdiction: string;
  assignee: string;
}

/**
 * Regulatory Reporting Grid Component
 * Uses AG Grid v31.x with Enterprise features
 */
const RegReportingGrid: React.FC = () => {
  const [gridApi, setGridApi] = useState<GridApi | null>(null);
  
  // Sample data for regulatory reports
  const [rowData] = useState<RegReport[]>([
    {
      id: 'REG-001',
      reportName: 'CCAR Stress Test Report',
      reportType: 'CCAR',
      status: 'Submitted',
      submissionDate: '2024-01-15',
      regulator: 'Federal Reserve',
      jurisdiction: 'US',
      assignee: 'John Smith',
    },
    {
      id: 'REG-002',
      reportName: 'Basel III Liquidity Report',
      reportType: 'Basel III',
      status: 'Draft',
      submissionDate: '2024-01-20',
      regulator: 'BIS',
      jurisdiction: 'Global',
      assignee: 'Jane Doe',
    },
    {
      id: 'REG-003',
      reportName: 'MiFID II Transaction Report',
      reportType: 'MiFID II',
      status: 'Approved',
      submissionDate: '2024-01-10',
      regulator: 'ESMA',
      jurisdiction: 'EU',
      assignee: 'Bob Wilson',
    },
    {
      id: 'REG-004',
      reportName: 'Dodd-Frank Swap Report',
      reportType: 'Dodd-Frank',
      status: 'Submitted',
      submissionDate: '2024-01-18',
      regulator: 'CFTC',
      jurisdiction: 'US',
      assignee: 'Alice Brown',
    },
    {
      id: 'REG-005',
      reportName: 'GDPR Compliance Report',
      reportType: 'GDPR',
      status: 'Rejected',
      submissionDate: '2024-01-12',
      regulator: 'ICO',
      jurisdiction: 'UK',
      assignee: 'Charlie Davis',
    },
  ]);

  // Column definitions with AG Grid v31 features
  const columnDefs = useMemo<ColDef<RegReport>[]>(() => [
    {
      field: 'id',
      headerName: 'Report ID',
      width: 120,
      pinned: 'left',
    },
    {
      field: 'reportName',
      headerName: 'Report Name',
      flex: 1,
      minWidth: 200,
      filter: 'agTextColumnFilter',
    },
    {
      field: 'reportType',
      headerName: 'Type',
      width: 120,
      filter: 'agSetColumnFilter',
    },
    {
      field: 'status',
      headerName: 'Status',
      width: 120,
      cellRenderer: (params: { value: string }) => {
        const statusColors: Record<string, string> = {
          Draft: '#718096',
          Submitted: '#3182ce',
          Approved: '#38a169',
          Rejected: '#e53e3e',
        };
        const color = statusColors[params.value] || '#718096';
        return (
          <span
            style={{
              color,
              fontWeight: 500,
              padding: '2px 8px',
              borderRadius: '4px',
              backgroundColor: `${color}20`,
            }}
          >
            {params.value}
          </span>
        );
      },
    },
    {
      field: 'submissionDate',
      headerName: 'Submission Date',
      width: 150,
      filter: 'agDateColumnFilter',
    },
    {
      field: 'regulator',
      headerName: 'Regulator',
      width: 140,
      filter: 'agSetColumnFilter',
    },
    {
      field: 'jurisdiction',
      headerName: 'Jurisdiction',
      width: 120,
      filter: 'agSetColumnFilter',
    },
    {
      field: 'assignee',
      headerName: 'Assignee',
      width: 130,
      filter: 'agTextColumnFilter',
    },
  ], []);

  // Default column definition
  const defaultColDef = useMemo<ColDef>(() => ({
    sortable: true,
    resizable: true,
    filter: true,
  }), []);

  const onGridReady = useCallback((params: GridReadyEvent) => {
    setGridApi(params.api);
  }, []);

  return (
    <div className="grid-container">
      <div className="grid-toolbar">
        <button
          className="toolbar-button"
          onClick={() => gridApi?.exportDataAsCsv()}
        >
          Export CSV
        </button>
        <button
          className="toolbar-button"
          onClick={() => gridApi?.setFilterModel(null)}
        >
          Clear Filters
        </button>
      </div>
      <div className="ag-theme-alpine" style={{ height: 400, width: '100%' }}>
        <AgGridReact
          rowData={rowData}
          columnDefs={columnDefs}
          defaultColDef={defaultColDef}
          onGridReady={onGridReady}
          rowSelection="multiple"
          animateRows={true}
          pagination={true}
          paginationPageSize={10}
        />
      </div>
    </div>
  );
};

export default RegReportingGrid;
